version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.1
    ports:
      - "2181:2181"
    env_file:
      - .env

  kafka:
    image: confluentinc/cp-kafka:6.1.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29094:29094"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server kafka:29093 --list || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 10

  init-kafka:
    image: confluentinc/cp-kafka:6.1.1
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: ['/bin/sh', '-c']
    command: |
      "
      until kafka-topics --bootstrap-server kafka:29093 --list; do
        echo 'Waiting for Kafka...'
        sleep 5
      done
      kafka-topics --bootstrap-server kafka:29093 --create --if-not-exists \
        --topic agro.notification.requests --replication-factor 1 --partitions 3
      kafka-topics --bootstrap-server kafka:29093 --create --if-not-exists \
        --topic agro.notification.responses --replication-factor 1 --partitions 3
      echo 'Topics created'
      "