agro:
  notification:
    requests: "agro.notification.requests"
    responses: "agro.notification.responses"

spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/${MONGO_DATABASE}?authSource=admin
  mail:
    host: smtp.gmail.com
    port: 587
    username: kabopok@gmail.com
    password: "juba gxjk tqum vumx"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          debug: true
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVER}
    consumer:
      group-id: notificationServiceGroup
  mongock:
    migration-scan-package: agroscience.notifications.migrations
server:
  port: ${SERVER_PORT}